/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class ConfirmationPage extends javax.swing.JFrame {

    
    public ConfirmationPage(String movie, String time, String seats, double sPrice, String snacks, double snPrice, double total) {
    initComponents(); 
    
   
    lblMO.setText(movie);
    lblTime.setText(time);
    lblSeats.setText(seats);
    lblSeatsP.setText(sPrice + " JD");
    lblSn.setText(snacks);
    lblSNACKSP.setText(snPrice + " JD");
    lblTPrice.setText(total + " JD");
}
    
  
  public ConfirmationPage() {
    initComponents();
  }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new javax.swing.JPanel();
        lblC = new javax.swing.JLabel();
        btnCF = new javax.swing.JButton();
        btnB = new javax.swing.JButton();
        pnl2 = new javax.swing.JPanel();
        lblYD = new javax.swing.JLabel();
        lblYN = new javax.swing.JLabel();
        txtYN = new javax.swing.JTextField();
        lblYNP = new javax.swing.JLabel();
        txtYNP = new javax.swing.JTextField();
        pnl3 = new javax.swing.JPanel();
        lblBS = new javax.swing.JLabel();
        lblM = new javax.swing.JLabel();
        lblMO = new javax.swing.JLabel();
        lblS = new javax.swing.JLabel();
        lblSeats = new javax.swing.JLabel();
        lblT = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblSNACKS = new javax.swing.JLabel();
        lblSn = new javax.swing.JLabel();
        lblSnPr = new javax.swing.JLabel();
        lblSNACKSP = new javax.swing.JLabel();
        lblSP = new javax.swing.JLabel();
        lblSeatsP = new javax.swing.JLabel();
        lblTP = new javax.swing.JLabel();
        lblTPrice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Booking Confirmation");
        setResizable(false);

        pnl1.setBackground(new java.awt.Color(0, 0, 0));

        lblC.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblC.setForeground(new java.awt.Color(194, 30, 86));
        lblC.setText("BOOKING CONFIRMATION");

        btnCF.setBackground(new java.awt.Color(194, 30, 86));
        btnCF.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnCF.setForeground(new java.awt.Color(255, 255, 255));
        btnCF.setText("CONFIRM & FINISH ");
        btnCF.setContentAreaFilled(false);
        btnCF.setOpaque(true);
        btnCF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCFActionPerformed(evt);
            }
        });

        btnB.setBackground(new java.awt.Color(194, 30, 86));
        btnB.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnB.setForeground(new java.awt.Color(255, 255, 255));
        btnB.setText("BACK");
        btnB.setContentAreaFilled(false);
        btnB.setOpaque(true);
        btnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBActionPerformed(evt);
            }
        });

        pnl2.setBackground(new java.awt.Color(0, 0, 0));

        lblYD.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        lblYD.setForeground(new java.awt.Color(194, 30, 86));
        lblYD.setText("Your Details");

        lblYN.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblYN.setForeground(new java.awt.Color(255, 255, 255));
        lblYN.setText("YOUR NAME : ");

        txtYN.setBackground(new java.awt.Color(255, 202, 228));
        txtYN.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        lblYNP.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblYNP.setForeground(new java.awt.Color(255, 255, 255));
        lblYNP.setText("YOUR NUMBER ( PHONE) : ");

        txtYNP.setBackground(new java.awt.Color(255, 202, 228));
        txtYNP.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        javax.swing.GroupLayout pnl2Layout = new javax.swing.GroupLayout(pnl2);
        pnl2.setLayout(pnl2Layout);
        pnl2Layout.setHorizontalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtYN)
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblYD)
                            .addComponent(lblYN)
                            .addComponent(lblYNP))
                        .addGap(0, 212, Short.MAX_VALUE))
                    .addComponent(txtYNP))
                .addContainerGap())
        );
        pnl2Layout.setVerticalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblYD)
                .addGap(27, 27, 27)
                .addComponent(lblYN)
                .addGap(18, 18, 18)
                .addComponent(txtYN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblYNP)
                .addGap(18, 18, 18)
                .addComponent(txtYNP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnl3.setBackground(new java.awt.Color(0, 0, 0));

        lblBS.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        lblBS.setForeground(new java.awt.Color(194, 30, 86));
        lblBS.setText("Booking Summary  ");

        lblM.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblM.setForeground(new java.awt.Color(255, 255, 255));
        lblM.setText("Movie : ");

        lblMO.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblMO.setForeground(new java.awt.Color(255, 255, 255));
        lblMO.setText("M");

        lblS.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblS.setForeground(new java.awt.Color(255, 255, 255));
        lblS.setText("Seats :  ");

        lblSeats.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblSeats.setForeground(new java.awt.Color(255, 255, 255));
        lblSeats.setText("SEATS");

        lblT.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblT.setForeground(new java.awt.Color(255, 255, 255));
        lblT.setText("Time : ");

        lblTime.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setText("T");

        lblSNACKS.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblSNACKS.setForeground(new java.awt.Color(255, 255, 255));
        lblSNACKS.setText("Snacks :");

        lblSn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblSn.setForeground(new java.awt.Color(255, 255, 255));
        lblSn.setText("SNACKS");

        lblSnPr.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblSnPr.setForeground(new java.awt.Color(255, 255, 255));
        lblSnPr.setText("Snacks Price :  ");

        lblSNACKSP.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblSNACKSP.setForeground(new java.awt.Color(255, 255, 255));
        lblSNACKSP.setText("SNACKS P");

        lblSP.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblSP.setForeground(new java.awt.Color(255, 255, 255));
        lblSP.setText("Seats Price :  ");

        lblSeatsP.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblSeatsP.setForeground(new java.awt.Color(255, 255, 255));
        lblSeatsP.setText("SEATS P");

        lblTP.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblTP.setForeground(new java.awt.Color(255, 255, 255));
        lblTP.setText("Total Price: ");

        lblTPrice.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblTPrice.setForeground(new java.awt.Color(255, 255, 255));
        lblTPrice.setText("TP");

        javax.swing.GroupLayout pnl3Layout = new javax.swing.GroupLayout(pnl3);
        pnl3.setLayout(pnl3Layout);
        pnl3Layout.setHorizontalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBS)
                    .addComponent(lblM)
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(lblMO))
                    .addComponent(lblS)
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(lblSeats))
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblT)
                        .addGap(5, 5, 5)
                        .addComponent(lblTime))
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl3Layout.createSequentialGroup()
                                .addComponent(lblSNACKS)
                                .addGap(6, 6, 6)
                                .addComponent(lblSn))
                            .addGroup(pnl3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnl3Layout.createSequentialGroup()
                                        .addComponent(lblSP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblSeatsP))
                                    .addGroup(pnl3Layout.createSequentialGroup()
                                        .addComponent(lblTP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTPrice))
                                    .addGroup(pnl3Layout.createSequentialGroup()
                                        .addComponent(lblSnPr)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblSNACKSP)))))))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        pnl3Layout.setVerticalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBS)
                .addGap(28, 28, 28)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblM)
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblMO)))
                .addGap(18, 18, 18)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblS)
                    .addComponent(lblSeats))
                .addGap(18, 18, 18)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblT))
                    .addComponent(lblTime))
                .addGap(18, 18, 18)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSNACKS)
                    .addComponent(lblSn))
                .addGap(18, 18, 18)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSnPr)
                    .addComponent(lblSNACKSP))
                .addGap(18, 18, 18)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSP)
                    .addComponent(lblSeatsP))
                .addGap(18, 18, 18)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTP)
                    .addComponent(lblTPrice))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnB)
                        .addGap(166, 166, 166)
                        .addComponent(btnCF))
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnl3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(lblC)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblC)
                .addGap(78, 78, 78)
                .addComponent(pnl3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(pnl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnB)
                        .addGap(27, 27, 27))
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnCF)
                        .addContainerGap(53, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBActionPerformed
        // TODO add your handling code here:
        SnacksPage Snack = new SnacksPage();
        Snack.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBActionPerformed

    private void btnCFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCFActionPerformed
        // TODO add your handling code here:
         String name = txtYN.getText();
    String phone = txtYNP.getText();

   
    if (name.isEmpty() || phone.isEmpty()) {
       
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Please enter your Name and Phone Number to complete the booking!", 
            "Missing Information", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
    } else {
       
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Thank you " + name + "!\nYour booking for MonsterX Cinema is confirmed.\nWe sent a message to: " + phone, 
            "Booking Successful", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
       
        System.exit(0); 
        
//        JOptionPane.showMessageDialog(this, "Booking Confirmed Successfully!");
    }   
    }//GEN-LAST:event_btnCFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmationPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnCF;
    private javax.swing.JLabel lblBS;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblM;
    private javax.swing.JLabel lblMO;
    private javax.swing.JLabel lblS;
    private javax.swing.JLabel lblSNACKS;
    private javax.swing.JLabel lblSNACKSP;
    private javax.swing.JLabel lblSP;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblSeatsP;
    private javax.swing.JLabel lblSn;
    private javax.swing.JLabel lblSnPr;
    private javax.swing.JLabel lblT;
    private javax.swing.JLabel lblTP;
    private javax.swing.JLabel lblTPrice;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblYD;
    private javax.swing.JLabel lblYN;
    private javax.swing.JLabel lblYNP;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl3;
    private javax.swing.JTextField txtYN;
    private javax.swing.JTextField txtYNP;
    // End of variables declaration//GEN-END:variables
}
