/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

//import javax.swing.ImageIcon;

/**
 *
 * @author ASUS
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
      
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new javax.swing.JPanel();
        lblM = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        lblPOSTA = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        btnD2 = new javax.swing.JButton();
        lblPOSTH = new javax.swing.JLabel();
        lblH = new javax.swing.JLabel();
        btnD1 = new javax.swing.JButton();
        lblPOSTIT = new javax.swing.JLabel();
        lblIT = new javax.swing.JLabel();
        btnD3 = new javax.swing.JButton();
        lblPOSTS = new javax.swing.JLabel();
        lblS = new javax.swing.JLabel();
        btnD4 = new javax.swing.JButton();
        lblCont = new javax.swing.JLabel();
        btnL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cinema Booking System");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl1.setBackground(new java.awt.Color(0, 0, 0));
        pnl1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblM.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        lblM.setForeground(new java.awt.Color(194, 30, 86));
        lblM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblM.setText("MONSTERX");
        pnl1.add(lblM, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 210, -1));

        lblB.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblB.setForeground(new java.awt.Color(255, 255, 255));
        lblB.setText("Browse and book your favorite movies");
        pnl1.add(lblB, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 350, -1));

        lblPOSTA.setForeground(new java.awt.Color(255, 255, 255));
        lblPOSTA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AVE.png"))); // NOI18N
        lblPOSTA.setText("jLabel12");
        pnl1.add(lblPOSTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 230, 340));

        lblA.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblA.setForeground(new java.awt.Color(255, 255, 255));
        lblA.setText("<html>\n   AVENGERS <br>\nINFINITY WAR\n</html>\n");
        pnl1.add(lblA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, -1, -1));

        btnD2.setBackground(new java.awt.Color(194, 30, 86));
        btnD2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnD2.setForeground(new java.awt.Color(255, 255, 255));
        btnD2.setText("Details");
        btnD2.setContentAreaFilled(false);
        btnD2.setOpaque(true);
        btnD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD2ActionPerformed(evt);
            }
        });
        pnl1.add(btnD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, -1, -1));

        lblPOSTH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Home.png"))); // NOI18N
        lblPOSTH.setText("jLabel5");
        pnl1.add(lblPOSTH, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 240, 340));

        lblH.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblH.setForeground(new java.awt.Color(255, 255, 255));
        lblH.setText("HOMEALONE");
        pnl1.add(lblH, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, -1, -1));

        btnD1.setBackground(new java.awt.Color(194, 30, 86));
        btnD1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnD1.setForeground(new java.awt.Color(255, 255, 255));
        btnD1.setText("Details");
        btnD1.setContentAreaFilled(false);
        btnD1.setOpaque(true);
        btnD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD1ActionPerformed(evt);
            }
        });
        pnl1.add(btnD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, -1, -1));

        lblPOSTIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/it.png"))); // NOI18N
        lblPOSTIT.setText("jLabel6");
        pnl1.add(lblPOSTIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 230, 348));

        lblIT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblIT.setForeground(new java.awt.Color(255, 255, 255));
        lblIT.setText("IT\n");
        pnl1.add(lblIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 880, -1, -1));

        btnD3.setBackground(new java.awt.Color(194, 30, 86));
        btnD3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnD3.setForeground(new java.awt.Color(255, 255, 255));
        btnD3.setText("Details");
        btnD3.setContentAreaFilled(false);
        btnD3.setOpaque(true);
        btnD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD3ActionPerformed(evt);
            }
        });
        pnl1.add(btnD3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 880, -1, -1));

        lblPOSTS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SPIDER.png"))); // NOI18N
        lblPOSTS.setText("jLabel4");
        pnl1.add(lblPOSTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, 242, -1));

        lblS.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblS.setForeground(new java.awt.Color(255, 255, 255));
        lblS.setText("<html>\nSPIDERMAN <br>\nNO WAY HOME\n</html>\n");
        pnl1.add(lblS, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 870, -1, -1));

        btnD4.setBackground(new java.awt.Color(194, 30, 86));
        btnD4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnD4.setForeground(new java.awt.Color(255, 255, 255));
        btnD4.setText("Details");
        btnD4.setContentAreaFilled(false);
        btnD4.setOpaque(true);
        btnD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD4ActionPerformed(evt);
            }
        });
        pnl1.add(btnD4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 880, -1, -1));

        lblCont.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblCont.setForeground(new java.awt.Color(255, 255, 255));
        lblCont.setText("Contact | Phone | Instagram");
        pnl1.add(lblCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 940, 260, -1));

        btnL.setBackground(new java.awt.Color(194, 30, 86));
        btnL.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnL.setForeground(new java.awt.Color(255, 255, 255));
        btnL.setText("Logout");
        btnL.setContentAreaFilled(false);
        btnL.setOpaque(true);
        btnL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLActionPerformed(evt);
            }
        });
        pnl1.add(btnL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 940, -1, 30));

        getContentPane().add(pnl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 770, 980));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLActionPerformed
        // TODO add your handling code here:
       
        Login Lo = new Login();
        Lo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLActionPerformed

    private void btnD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD1ActionPerformed
     
        String img = "/Images/Home.png"; 
        MovieDetails details = new MovieDetails("103 min","Home Alone", "Comedy / Family", "7.7/10", "An eight-year-old troublemaker must protect "
                + "his house from a pair of burglars when he is accidentally left home alone by his family during Christmas vacation. "
                + "He uses his creativity and a series of hilarious booby traps to defend his home in this classic family comedy.", img);
        details.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnD1ActionPerformed

    private void btnD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD3ActionPerformed
      
        String img = "/Images/it.png"; 
        MovieDetails details = new MovieDetails("135 min","IT Chapter Two", "Horror / Fantasy", "6.5/10", "In the summer of 1989, a group of bullied kids band together to destroy a shape-shifting monster, "
                + "which disguises itself as a clown and preys on the children of Derry. "
                + "They must overcome their own personal fears to battle the murderous bloodthirsty clown known as Pennywise.", img);
        details.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnD3ActionPerformed

    private void btnD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD4ActionPerformed
        // TODO add your handling code here:
                                       
    String img = "/Images/SPIDER.png"; 
    MovieDetails details = new MovieDetails("148 min","Spider-Man: No Way Home", "Action / Adventure", "8.5/10", "With Spider-Man's identity now revealed,"
            + " Peter asks Doctor Strange for help. When a spell goes wrong, "
            + "dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man in his biggest challenge yet, "
            + "as he battles villains from across the multiverse.", img);
    details.setVisible(true);
    this.dispose();


        
    }//GEN-LAST:event_btnD4ActionPerformed

    private void btnD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD2ActionPerformed
     
    String img = "/Images/AVE.png"; 
    MovieDetails details = new MovieDetails("149 min","Avengers: Infinity War", "Action / Sci-Fi", "8.4/10", "The Avengers and their allies must be willing to sacrifice all in an attempt "
            + "to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe. "
            + "It is a cinematic journey ten years in the making that spans the entire Marvel Cinematic Universe.", img);
    details.setVisible(true);
    this.dispose();


    }//GEN-LAST:event_btnD2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnD1;
    private javax.swing.JButton btnD2;
    private javax.swing.JButton btnD3;
    private javax.swing.JButton btnD4;
    private javax.swing.JButton btnL;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblCont;
    private javax.swing.JLabel lblH;
    private javax.swing.JLabel lblIT;
    private javax.swing.JLabel lblM;
    private javax.swing.JLabel lblPOSTA;
    private javax.swing.JLabel lblPOSTH;
    private javax.swing.JLabel lblPOSTIT;
    private javax.swing.JLabel lblPOSTS;
    private javax.swing.JLabel lblS;
    private javax.swing.JPanel pnl1;
    // End of variables declaration//GEN-END:variables
}
