/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author ASUS
 */
public class MovieDetails extends javax.swing.JFrame {
    
    String timeSelected = ""; 


    /**
     * Creates new form MovieDetails
     */

    public MovieDetails(String Min,String name, String genre, String rating, String description, String imgPath) {
        initComponents();
        lblM.setText(Min);
        lblMN.setText(name);
        lblG.setText(genre);
        lblR.setText(rating);
        lblD.setText("<html><div style='width:300px;'>" + description + "</div></html>");
    
 
//     java.net.URL imgURL = getClass().getResource(imgPath);
//    if (imgURL != null) {
//        System.out.println("✅ تم إيجاد الصورة بنجاح في المسار: " + imgPath);
//        lblPoster.setIcon(new javax.swing.ImageIcon(imgURL));
//    } else {
//        System.err.println("❌ خطأ: لم يتم العثور على الصورة في المسار: " + imgPath);
//        System.err.println("تأكدي أن الصورة موجودة فعلياً في فولدر الصور داخل المشروع.");
//    }
 


    // كود فحص وتكبير الصورة
    java.net.URL imgURL = getClass().getResource(imgPath);
    if (imgURL != null) {
        System.out.println("✅ تم إيجاد الصورة بنجاح، جاري التكبير...");
        
        // جلب عرض وطول الـ Label من الـ Design تلقائياً
        int w = lblPoster.getWidth();
        int h = lblPoster.getHeight();
        
        // إذا كان العرض أو الطول صفر (بصير أحياناً قبل ما تظهر الشاشة)، بنحط قيم افتراضية
        if(w <= 0) w = 300; 
        if(h <= 0) h = 400;
        
        lblPoster.setIcon(resizeImage(imgURL, w, h));
    } else {
        System.err.println("❌ خطأ: لم يتم العثور على الصورة: " + imgPath);
    }
  }
    public MovieDetails() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new javax.swing.JPanel();
        lblMI = new javax.swing.JLabel();
        lblPoster = new javax.swing.JLabel();
        lblM = new javax.swing.JLabel();
        lblMOV = new javax.swing.JLabel();
        lblMN = new javax.swing.JLabel();
        lblGE = new javax.swing.JLabel();
        lblG = new javax.swing.JLabel();
        lblRA = new javax.swing.JLabel();
        lblR = new javax.swing.JLabel();
        lblDes = new javax.swing.JLabel();
        lblD = new javax.swing.JLabel();
        lblST = new javax.swing.JLabel();
        btn8 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btnBook = new javax.swing.JButton();
        btnB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Movie Details");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl1.setBackground(new java.awt.Color(0, 0, 0));
        pnl1.setForeground(new java.awt.Color(255, 255, 255));
        pnl1.setPreferredSize(new java.awt.Dimension(782, 1000));
        pnl1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMI.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblMI.setForeground(new java.awt.Color(255, 255, 255));
        lblMI.setText("Movie Info");
        pnl1.add(lblMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 13, -1, -1));

        lblPoster.setBackground(new java.awt.Color(255, 177, 203));
        lblPoster.setForeground(new java.awt.Color(255, 255, 255));
        lblPoster.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPoster.setText("jLabel2");
        pnl1.add(lblPoster, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 63, 478, 600));

        lblM.setForeground(new java.awt.Color(255, 255, 255));
        lblM.setText("148 m");
        pnl1.add(lblM, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 670, -1, -1));

        lblMOV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMOV.setForeground(new java.awt.Color(255, 255, 255));
        lblMOV.setText("Movie Name : ");
        pnl1.add(lblMOV, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 693, -1, -1));

        lblMN.setForeground(new java.awt.Color(255, 255, 255));
        lblMN.setText("MOVIE NAME");
        pnl1.add(lblMN, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 694, -1, -1));

        lblGE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGE.setForeground(new java.awt.Color(255, 255, 255));
        lblGE.setText("Genre : ");
        pnl1.add(lblGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 723, -1, -1));

        lblG.setForeground(new java.awt.Color(255, 255, 255));
        lblG.setText("GENRE");
        pnl1.add(lblG, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 724, -1, -1));

        lblRA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRA.setForeground(new java.awt.Color(255, 255, 255));
        lblRA.setText("Rating : ");
        pnl1.add(lblRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 754, -1, -1));

        lblR.setForeground(new java.awt.Color(255, 255, 255));
        lblR.setText("RATING");
        pnl1.add(lblR, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 755, -1, -1));

        lblDes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDes.setForeground(new java.awt.Color(255, 255, 255));
        lblDes.setText("Description : ");
        pnl1.add(lblDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 781, -1, -1));

        lblD.setForeground(new java.awt.Color(255, 255, 255));
        lblD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblD.setText("DESCRIPATION");
        pnl1.add(lblD, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 781, 416, 80));

        lblST.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblST.setForeground(new java.awt.Color(255, 255, 255));
        lblST.setText("Show Time : ");
        pnl1.add(lblST, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 890, -1, -1));

        btn8.setBackground(new java.awt.Color(194, 30, 86));
        btn8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setText("8:00PM");
        btn8.setContentAreaFilled(false);
        btn8.setOpaque(true);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        pnl1.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 890, -1, -1));

        btn10.setBackground(new java.awt.Color(194, 30, 86));
        btn10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn10.setForeground(new java.awt.Color(255, 255, 255));
        btn10.setText("10:00PM");
        btn10.setContentAreaFilled(false);
        btn10.setOpaque(true);
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        pnl1.add(btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 890, -1, -1));

        btn12.setBackground(new java.awt.Color(194, 30, 86));
        btn12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn12.setForeground(new java.awt.Color(255, 255, 255));
        btn12.setText("12:00PM");
        btn12.setContentAreaFilled(false);
        btn12.setOpaque(true);
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });
        pnl1.add(btn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 890, -1, -1));

        btnBook.setBackground(new java.awt.Color(194, 30, 86));
        btnBook.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnBook.setForeground(new java.awt.Color(255, 255, 255));
        btnBook.setText("BOOK TICKETS");
        btnBook.setContentAreaFilled(false);
        btnBook.setOpaque(true);
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });
        pnl1.add(btnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 940, -1, -1));

        btnB.setBackground(new java.awt.Color(194, 30, 86));
        btnB.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnB.setForeground(new java.awt.Color(255, 255, 255));
        btnB.setText("Back");
        btnB.setContentAreaFilled(false);
        btnB.setOpaque(true);
        btnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBActionPerformed(evt);
            }
        });
        pnl1.add(btnB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 940, -1, -1));

        getContentPane().add(pnl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, 990));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBActionPerformed
        // TODO add your handling code here:
        HomePage Home = new HomePage();
        Home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
           // 1. التأكد إن المستخدم اختار وقت (عشان ما يروح للكراسي بدون وقت)
    if (timeSelected.equals("")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a time first!");
        return;
    }

    // 2. أخذ اسم الفيلم (تأكدي إن lblTitle هو اسم الليبل اللي فيه اسم الفيلم عندك)
    String movie = lblMN.getText();

    // 3. الانتقال لصفحة الكراسي وإرسال المعلومات
    // ملاحظة: لازم تكوني معدلة الـ Constructor في صفحة الكراسي ليستقبل (movie, timeSelected)
    new SeatSelection(movie, timeSelected).setVisible(true);
    
    // 4. إغلاق الصفحة الحالية
    this.dispose();

    }//GEN-LAST:event_btnBookActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
         timeSelected = "8:00 PM";
   
    btn8.setBackground(java.awt.Color.PINK); 
    btn10.setBackground(java.awt.Color.GRAY);
    btn12.setBackground(java.awt.Color.GRAY);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        // TODO add your handling code here:
            timeSelected = "10:00 PM";
   
    btn8.setBackground(java.awt.Color.GRAY); 
    btn10.setBackground(java.awt.Color.PINK);
    btn12.setBackground(java.awt.Color.GRAY);
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        // TODO add your handling code here:
            timeSelected = "12:00 PM";
   
    btn8.setBackground(java.awt.Color.GRAY); 
    btn10.setBackground(java.awt.Color.GRAY);
    btn12.setBackground(java.awt.Color.PINK);
    }//GEN-LAST:event_btn12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieDetails().setVisible(true);
            }
        });
        
    }

        // --- دالة تكبير الصورة ---
    public javax.swing.ImageIcon resizeImage(java.net.URL imgURL, int width, int height) {
        javax.swing.ImageIcon myImage = new javax.swing.ImageIcon(imgURL);
        java.awt.Image img = myImage.getImage();
        java.awt.Image newImg = img.getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH);
        return new javax.swing.ImageIcon(newImg);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnBook;
    private javax.swing.JLabel lblD;
    private javax.swing.JLabel lblDes;
    private javax.swing.JLabel lblG;
    private javax.swing.JLabel lblGE;
    private javax.swing.JLabel lblM;
    private javax.swing.JLabel lblMI;
    private javax.swing.JLabel lblMN;
    private javax.swing.JLabel lblMOV;
    private javax.swing.JLabel lblPoster;
    private javax.swing.JLabel lblR;
    private javax.swing.JLabel lblRA;
    private javax.swing.JLabel lblST;
    private javax.swing.JPanel pnl1;
    // End of variables declaration//GEN-END:variables
}
