/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author ASUS
 */
public class SnacksPage extends javax.swing.JFrame {
    
     String movieName, movieTime, movieSeats;
    double seatsPrice;
    int qtyP = 0;
    
 int qtyC = 0, qtyN = 0, qtyM = 0; 
 double pP = 2.5, pC = 1.5, pN = 3.0, pM = 1.5; 


     public SnacksPage(){
          initComponents();
     } 
    
    /**
     * Creates new form SnacksPage
     */
    public SnacksPage(String m, String t, String s, double p) {
        
        initComponents();
        
        this.movieName = m;
        this.movieTime = t;
        this.movieSeats = s;
        this.seatsPrice = p;
    }
    
  private void updateTotal() {
  
    double total = (qtyP * pP) + (qtyC * pC) + (qtyN * pN) + (qtyM * pM);
    lblSP.setText("Total Price: " + total + " JD");

    String items = ""; 
    
    if (qtyP > 0) { items += qtyP + " * Popcorn, "; }
    if (qtyC > 0) { items += qtyC + " * Chocolate, "; }
    if (qtyN > 0) { items += qtyN + " * Nachos, "; } 
    if (qtyM > 0) { items += qtyM + " * Matrix, "; }


    if (items.endsWith(", ")) {
        items = items.substring(0, items.length() - 2);
    }
    
    
    if (items.isEmpty()) {
        items = "None";
    }


    lblss.setText(items); 
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new javax.swing.JPanel();
        lblFD = new javax.swing.JLabel();
        lblPOSTP = new javax.swing.JLabel();
        lblP = new javax.swing.JLabel();
        btnPp = new javax.swing.JButton();
        lblQP = new javax.swing.JLabel();
        btnPm = new javax.swing.JButton();
        lblPOSTC = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();
        btnCp = new javax.swing.JButton();
        lblQC = new javax.swing.JLabel();
        btnCm = new javax.swing.JButton();
        lblPOSTN = new javax.swing.JLabel();
        lblN = new javax.swing.JLabel();
        btnNp = new javax.swing.JButton();
        lblQN = new javax.swing.JLabel();
        btnNm = new javax.swing.JButton();
        lblPOSTM = new javax.swing.JLabel();
        lblM = new javax.swing.JLabel();
        btnMp = new javax.swing.JButton();
        lblQM = new javax.swing.JLabel();
        btnMm = new javax.swing.JButton();
        lblSS = new javax.swing.JLabel();
        lblss = new javax.swing.JLabel();
        lblSP = new javax.swing.JLabel();
        btnCont = new javax.swing.JButton();
        btnB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Choose Snacks");
        setBackground(new java.awt.Color(203, 0, 0));
        setResizable(false);

        pnl1.setBackground(new java.awt.Color(0, 0, 0));

        lblFD.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblFD.setForeground(new java.awt.Color(255, 255, 255));
        lblFD.setText("FOODS & DRINKS");

        lblPOSTP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Screenshot 2026-05-23 113233.png"))); // NOI18N
        lblPOSTP.setText("jLabel2");

        lblP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblP.setForeground(new java.awt.Color(255, 255, 255));
        lblP.setText("POPCORN ");

        btnPp.setBackground(new java.awt.Color(194, 30, 86));
        btnPp.setForeground(new java.awt.Color(255, 255, 255));
        btnPp.setText("+");
        btnPp.setContentAreaFilled(false);
        btnPp.setOpaque(true);
        btnPp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPpActionPerformed(evt);
            }
        });

        lblQP.setForeground(new java.awt.Color(255, 255, 255));
        lblQP.setText("0");

        btnPm.setBackground(new java.awt.Color(194, 30, 86));
        btnPm.setForeground(new java.awt.Color(255, 255, 255));
        btnPm.setText("-");
        btnPm.setContentAreaFilled(false);
        btnPm.setOpaque(true);
        btnPm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPmActionPerformed(evt);
            }
        });

        lblPOSTC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Screenshot 2026-05-23 115431.png"))); // NOI18N
        lblPOSTC.setText("jLabel6");

        lblC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblC.setForeground(new java.awt.Color(255, 255, 255));
        lblC.setText("CHOCOLATE");

        btnCp.setBackground(new java.awt.Color(194, 30, 86));
        btnCp.setForeground(new java.awt.Color(255, 255, 255));
        btnCp.setText("+");
        btnCp.setContentAreaFilled(false);
        btnCp.setOpaque(true);
        btnCp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCpActionPerformed(evt);
            }
        });

        lblQC.setForeground(new java.awt.Color(255, 255, 255));
        lblQC.setText("0");

        btnCm.setBackground(new java.awt.Color(194, 30, 86));
        btnCm.setForeground(new java.awt.Color(255, 255, 255));
        btnCm.setText("-");
        btnCm.setContentAreaFilled(false);
        btnCm.setOpaque(true);
        btnCm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCmActionPerformed(evt);
            }
        });

        lblPOSTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Screenshot 2026-05-23 120251.png"))); // NOI18N
        lblPOSTN.setText("jLabel4");

        lblN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblN.setForeground(new java.awt.Color(255, 255, 255));
        lblN.setText("Nachos");

        btnNp.setBackground(new java.awt.Color(194, 30, 86));
        btnNp.setForeground(new java.awt.Color(255, 255, 255));
        btnNp.setText("+");
        btnNp.setContentAreaFilled(false);
        btnNp.setOpaque(true);
        btnNp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNpActionPerformed(evt);
            }
        });

        lblQN.setForeground(new java.awt.Color(255, 255, 255));
        lblQN.setText("0");

        btnNm.setBackground(new java.awt.Color(194, 30, 86));
        btnNm.setForeground(new java.awt.Color(255, 255, 255));
        btnNm.setText("-");
        btnNm.setContentAreaFilled(false);
        btnNm.setOpaque(true);
        btnNm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNmActionPerformed(evt);
            }
        });

        lblPOSTM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Screenshot 2026-05-23 121607.png"))); // NOI18N

        lblM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblM.setForeground(new java.awt.Color(255, 255, 255));
        lblM.setText("MATRIX");

        btnMp.setBackground(new java.awt.Color(194, 30, 86));
        btnMp.setForeground(new java.awt.Color(255, 255, 255));
        btnMp.setText("+");
        btnMp.setContentAreaFilled(false);
        btnMp.setOpaque(true);
        btnMp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMpActionPerformed(evt);
            }
        });

        lblQM.setForeground(new java.awt.Color(255, 255, 255));
        lblQM.setText("0");

        btnMm.setBackground(new java.awt.Color(194, 30, 86));
        btnMm.setForeground(new java.awt.Color(255, 255, 255));
        btnMm.setText("-");
        btnMm.setContentAreaFilled(false);
        btnMm.setOpaque(true);
        btnMm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMmActionPerformed(evt);
            }
        });

        lblSS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSS.setForeground(new java.awt.Color(255, 255, 255));
        lblSS.setText("Selected Snacks : ");

        lblss.setForeground(new java.awt.Color(255, 255, 255));
        lblss.setText("SNACKS");

        lblSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSP.setForeground(new java.awt.Color(255, 255, 255));
        lblSP.setText("Snacks Price : ");

        btnCont.setBackground(new java.awt.Color(194, 30, 86));
        btnCont.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnCont.setForeground(new java.awt.Color(255, 255, 255));
        btnCont.setText("CONTONUE");
        btnCont.setContentAreaFilled(false);
        btnCont.setOpaque(true);
        btnCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContActionPerformed(evt);
            }
        });

        btnB.setBackground(new java.awt.Color(194, 30, 86));
        btnB.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnB.setForeground(new java.awt.Color(255, 255, 255));
        btnB.setText("BACK");
        btnB.setContentAreaFilled(false);
        btnB.setOpaque(true);
        btnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addComponent(lblPOSTN, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(173, 173, 173)
                        .addComponent(lblPOSTM, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPOSTP, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblP)
                                .addGap(26, 26, 26)
                                .addComponent(btnPp)
                                .addGap(11, 11, 11)
                                .addComponent(lblQP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPm))
                            .addGroup(pnl1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(lblN)
                                .addGap(26, 26, 26)
                                .addComponent(btnNp)
                                .addGap(11, 11, 11)
                                .addComponent(lblQN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNm)))
                        .addGap(175, 175, 175)
                        .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblC)
                                .addGap(26, 26, 26)
                                .addComponent(btnCp)
                                .addGap(11, 11, 11)
                                .addComponent(lblQC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCm))
                            .addComponent(lblPOSTC, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1Layout.createSequentialGroup()
                                .addComponent(lblM)
                                .addGap(26, 26, 26)
                                .addComponent(btnMp)
                                .addGap(11, 11, 11)
                                .addComponent(lblQM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMm)
                                .addGap(20, 20, 20))))
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl1Layout.createSequentialGroup()
                                .addComponent(btnB)
                                .addGap(191, 191, 191)
                                .addComponent(btnCont))
                            .addGroup(pnl1Layout.createSequentialGroup()
                                .addComponent(lblSS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblss))
                            .addComponent(lblSP))))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblFD)
                .addGap(306, 306, 306))
        );

        pnl1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnPm, btnPp});

        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFD)
                .addGap(23, 23, 23)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPOSTP, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPOSTC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPm)
                            .addComponent(btnPp)
                            .addComponent(lblP)
                            .addComponent(lblQP))
                        .addGap(30, 30, 30)
                        .addComponent(lblPOSTN, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCm)
                            .addComponent(btnCp)
                            .addComponent(lblC)
                            .addComponent(lblQC))
                        .addGap(33, 33, 33)
                        .addComponent(lblPOSTM, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMm)
                    .addComponent(btnMp)
                    .addComponent(lblM)
                    .addComponent(lblQM)
                    .addComponent(btnNm)
                    .addComponent(btnNp)
                    .addComponent(lblN)
                    .addComponent(lblQN))
                .addGap(38, 38, 38)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSS)
                    .addComponent(lblss))
                .addGap(13, 13, 13)
                .addComponent(lblSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCont)
                    .addComponent(btnB))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pnl1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnPm, btnPp});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContActionPerformed
        // TODO add your handling code here:
        // 1. حسبة سعر السناكات (بدون نقاط ...)
    double snacksPrice = (qtyP * pP) + (qtyC * pC) + (qtyN * pN) + (qtyM * pM);
    
    // 2. المجموع النهائي (سعر الكراسي اللي وصل + سعر السناكات)
    double total = seatsPrice + snacksPrice;
    
    // 3. نبعث كل المعلومات للصفحة الأخيرة (تأكدي إن الأسماء صح)
    // "Snacks List" هون رح نحط النص اللي فيه أسماء السناكات
    String allSnacks = lblss.getText(); 
    
   // في صفحة السناكات
    ConfirmationPage CON = new ConfirmationPage(movieName, movieTime, movieSeats, seatsPrice, allSnacks, snacksPrice, total);

    
    CON.setVisible(true); // فتح صفحة التأكيد
    this.setVisible(false);
        
      
    }//GEN-LAST:event_btnContActionPerformed

    private void btnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBActionPerformed
        // TODO add your handling code here:
        SeatSelection Seats = new SeatSelection();
        Seats.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBActionPerformed

    private void btnPpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPpActionPerformed
        // TODO add your handling code here:
        qtyP++; 
        lblQP.setText(String.valueOf(qtyP));     
        updateTotal();

    }//GEN-LAST:event_btnPpActionPerformed

    private void btnPmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPmActionPerformed
        // TODO add your handling code here:
        if (qtyP > 0) {
    qtyP--;
    lblQP.setText(String.valueOf(qtyP));
    updateTotal();
}

    }//GEN-LAST:event_btnPmActionPerformed

    private void btnCpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCpActionPerformed
        // TODO add your handling code here:
        qtyC++; 
lblQC.setText(String.valueOf(qtyC)); 
updateTotal();

    }//GEN-LAST:event_btnCpActionPerformed

    private void btnCmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCmActionPerformed
        // TODO add your handling code here:
        if (qtyC > 0) {
    qtyC--;
    lblQC.setText(String.valueOf(qtyC));
    updateTotal();
}

    }//GEN-LAST:event_btnCmActionPerformed

    private void btnNmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNmActionPerformed
        // TODO add your handling code here:
        if (qtyN > 0) {
    qtyN--;
    lblQN.setText(String.valueOf(qtyN));
    updateTotal();
}

    }//GEN-LAST:event_btnNmActionPerformed

    private void btnMmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMmActionPerformed
        // TODO add your handling code here:
        if (qtyM > 0) {
    qtyM--;
    lblQM.setText(String.valueOf(qtyM));
    updateTotal();
}

    }//GEN-LAST:event_btnMmActionPerformed

    private void btnNpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNpActionPerformed
        // TODO add your handling code here:
        qtyN++; 
lblQN.setText(String.valueOf(qtyN)); 
updateTotal();

    }//GEN-LAST:event_btnNpActionPerformed

    private void btnMpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMpActionPerformed
        // TODO add your handling code here:
        qtyM++; 
lblQM.setText(String.valueOf(qtyM)); 
updateTotal();

    }//GEN-LAST:event_btnMpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SnacksPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SnacksPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SnacksPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SnacksPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SnacksPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnCm;
    private javax.swing.JButton btnCont;
    private javax.swing.JButton btnCp;
    private javax.swing.JButton btnMm;
    private javax.swing.JButton btnMp;
    private javax.swing.JButton btnNm;
    private javax.swing.JButton btnNp;
    private javax.swing.JButton btnPm;
    private javax.swing.JButton btnPp;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblFD;
    private javax.swing.JLabel lblM;
    private javax.swing.JLabel lblN;
    private javax.swing.JLabel lblP;
    private javax.swing.JLabel lblPOSTC;
    private javax.swing.JLabel lblPOSTM;
    private javax.swing.JLabel lblPOSTN;
    private javax.swing.JLabel lblPOSTP;
    private javax.swing.JLabel lblQC;
    private javax.swing.JLabel lblQM;
    private javax.swing.JLabel lblQN;
    private javax.swing.JLabel lblQP;
    private javax.swing.JLabel lblSP;
    private javax.swing.JLabel lblSS;
    private javax.swing.JLabel lblss;
    private javax.swing.JPanel pnl1;
    // End of variables declaration//GEN-END:variables
}
